### ISSUE TITLE
magnet can´t be blank message

### ISSUE THREAD

**Issue by Hobbabobba** [sergiotapia/magnetissimo#85]
i get a lot of this error messages.
after running for more than 12 hrs i can just see 200+ torrents from EZTV.

anything i need to fix?

I set up magnetissimo on a Debian 7 vm.

```
 [info] [EZTV] Finding torrents in listing page: https://eztv.ag/page_0
 [info] [Demonoid] Downloading torrent from page: https://www.demonoid.pw/files/details/3641016/
 [error] Torrent skipped: The Pioneer Woman S07E05 16 Minute Meals Around the World 72 - Errors: magnet can't be blank
 [info] [Demonoid] Downloading torrent from page: https://www.demonoid.pw/files/details/3641010/
 [error] Torrent skipped: The Pioneer Woman S07E08 Happy Birthday Pa Pa HDTV x264-W4F - Errors: magnet can't be blank
 [info] [Leetx] Downloading torrent from page: https://1337x.to/torrent/2374099/Fansadox-Collection-451-Objection-Overruled-Comixchef-pdf/
 [error] Torrent skipped: Fansadox Collection 451 - Objection Overruled - Comixchef.pdf - Errors: magnet can't be blank
 [info] [Demonoid] Downloading torrent from page: https://www.demonoid.pw/files/details/3641012/
 [info] [EZTV] Finding torrents in listing page: https://eztv.ag/page_1
 [error] Torrent skipped: The Pioneer Woman S07E07 Gathering Bulls HDTV x264-W4F EZTV - Errors: magnet can't be blank
 [info] [Leetx] Downloading torrent from page: https://1337x.to/torrent/2373905/HorribleSubs-One-Piece-801-480p/
 [error] Torrent skipped: [HorribleSubs] One Piece - 801 [480p] - Errors: magnet can't be blank
```

**Comment by skwerlman** [comment]
are you using the `master` branch? `feature/cleanup` has many of these issues fixed, although Leetx is still broken there atm.

**Comment by swatgoss** [comment]
I get the same behavior after installing the `feature/general-cleanup` in a Debian 7 container on my dedicated server, its surprisingly slow !

So any infos about this ?

**Comment by skwerlman** [comment]
Wait, so you aren't seeing any torrents from sites other than eztv?

**Comment by swatgoss** [comment]
Absolutely, i let it run this night for ~8hours and this is the [actual state](https://user-images.githubusercontent.com/3351720/29307017-50f0f9be-81a0-11e7-8bb9-e0ee03f38a7c.png)
 of my webGUI
!

So there seems to be a problem with the crawlers for everything other than EZTV ...
In the logs I can see messages mostly about Demonoid and Leetx crawlers loading pages and errors skipping torrents because of magnets being blanks.

Any idea for where to start looking ?
I don't know elixir yet but this should be no problem to seek the differences between EZTV and Demonoid (+ the similarities between Demonoid and Leetx and why its not working)

**Comment by Hobbabobba** [comment]
`master` just crashed, so i started with `feature/general-cleanup` and it gives me the messages about blanks. besides EZTV, no torrents at all.

**Comment by tchoutri** [comment]
Hi, Is it still an observed behaviour?
