### ISSUE TITLE
Additional torrent sites

### ISSUE THREAD

**Issue by violtomte** [sergiotapia/magnetissimo#9]
https://zooqle.com/
https://eztv.ag/
http://gamestorrent.co/
http://www.btstorrent.cc/
https://concen.org/torrents/
https://metasearch.torrentproject.se/

**Comment by ProphetZarquon** [comment]
I would very much like to see a distributed DHT crawl implemented, as websites are transitory in nature & any given site/s may become unavailable for a variety of reasons.

A successful DHT crawl would also reveal working (active) torrents which are not listed on *any* known site. btdigg.org has gone down, apparently without ever publishing the crawler code, but perhaps with some research you could develop your own? The presentation "Crawling BitTorrent DHT for fun & profit" provides a very general idea how it is performed, though as yet I am not aware of any other implementations besides btdigg, which worked marvelously when it was up, providing torrent details & working magnet links even when meta-search sites fail to return a relevant result (all the more reason this needs to be done on a distributed basis, client-side, instead of relying on websites).

**Comment by sergiotapia** [comment]
Any links for more information on how to crawl DHT? I have no idea where to start on that but it does sound interesting (and more performant).

**Comment by Gank** [comment]
Maybe this would help you to get a jumpstart https://github.com/alanyang/dhtspider

Great project @sergiotapia !

**Comment by sergiotapia** [comment]
Awesome, I have literally not idea what DHT is at this stage, but I'm going to dive in and see how I come out at the end. Finger's crossed.

**Comment by agustif** [comment]
Some elixir stuff on DHT and torrents

https://github.com/cit/MLDHT
https://github.com/alehander42/tracker_request
https://github.com/alehander42/wire
https://github.com/folz/bento

**Comment by agustif** [comment]
Btw I would like to try on making the eztv scraper (Long time user of the website)

Beside parsers/eztv.ex creation

And some code on crawler.ex and download_worker.ex

Am I right? Or maybe Im underestimating the quantity of code required.

**Comment by sergiotapia** [comment]
@agustif That's pretty much it.

1. Create a parser for it
2. write some tests for the parser
3. Add to crawler.ex
4. Add to download_worker.ex
5. In config.exs add in a queue for eztv at 15 concurrency

Looking forward to the addition :)

**Comment by CharleyPeng1** [comment]
for DHT crawling there's this one, https://github.com/kevinlynx/dhtcrawler2 also written in erlang

**Comment by chid** [comment]
for DHT crawling there's this one, https://github.com/kevinlynx/dhtcrawler2 also written in erlang

**Comment by agustif** [comment]
Hey, Im on step 2 without passing tests. Should I finish that first? Or can I leave step 2 for final tuning.

It's not as easy due to EZTV having a lot of tables and little CSS. I've found some RegEx in others scrapers I should be able to use for the EZTV scraper.

Anyway, I would feel more confident before continuing and screwing forward to do a PR on a new-branch or somethin' and have someone look it out and give some guidance if continue or steer direction.

So lemme know, and thanks for open sourcing!! I have 1.5M torrents in my cpu, it's friggin' awesome to see Erlang do it's magic and max out my 8 threads on a 4790k hackintosh machine.

**Comment by sergiotapia** [comment]
Hey thanks for your interest in writing the additional parser.

I would write the tests before moving onto 3,4,5. It'll be easier for you to write the tests because you can run the parser tests pretty much instantly and make sure you're getting the data back.

Open up a pull request and I can give you a hand on getting it through. It looks much more complicated than it is I promise. :)

**Comment by agustif** [comment]
Sorry man, just spend 30min doing the wrong thing. Im gonna just upload my code.

**Comment by agustif** [comment]
Ok so I've checked out crawler and download_worker so not in the branch. https://github.com/agustif/magnetissimo/tree/parser-eztv

**Comment by agustif** [comment]
Gone ahead and opened the PR

**Comment by sergiotapia** [comment]
Your stuff landed on `master` :D

**Comment by agustif** [comment]
Should be leave some issue open to track integrated/proposed scrapers? so no new issues are open 

Wanted to add to the list of pending

http://www.gamestorrents.com/
http://elitetorrent.net/
http://www.mejortorrent.com/

**Comment by sergiotapia** [comment]
I think one issue per source is better than having a single 'to-do'.
